services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./code:/app/code
      - ./db:/app/db
      - ./posts:/app/posts
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1